"""
YOLOv8 Plant Disease Detection - Training Script
-------------------------------------------------
Trains YOLOv8m model for plant disease classification
Optimized for NVIDIA RTX 3050 6GB GPU

Author: Plant Disease Detection Project
Date: 2026
"""

import os
import sys
import yaml
import shutil
from pathlib import Path
from datetime import datetime
import torch
from ultralytics import YOLO

# ============================================================================
# CONFIGURATION
# ============================================================================

class Config:
    """Training configuration"""
    
    # Paths
    DATASET_ROOT = '/home/jeswin/Project/Plant Dataset'
    DATA_YAML = '/home/jeswin/Project/Plant Dataset'  # Generated by generate_data_yaml.py
    PROJECT_ROOT = './yolo_training_results'
    
    # Model settings
    MODEL_NAME = 'yolov8m-cls.pt'  # Medium model - good balance for 6GB GPU
    TASK = 'classify'  # Classification task (don't change this)
    
    # Training hyperparameters
    EPOCHS = 5
    BATCH_SIZE = 24  # Optimized for 6GB GPU
    IMG_SIZE = 224  # Standard classification size
    
    # Optimizer settings
    OPTIMIZER = 'AdamW'
    LR0 = 0.001  # Initial learning rate
    LRF = 0.01  # Final learning rate (lr0 * lrf)
    MOMENTUM = 0.937
    WEIGHT_DECAY = 0.0005
    
    # Data augmentation
    AUGMENT = True
    MOSAIC = 0.0  # Not used for classification
    MIXUP = 0.0   # Mixup augmentation
    COPY_PASTE = 0.0  # Not used for classification
    
    # Training settings
    PATIENCE = 20  # Early stopping patience
    DEVICE = 0  # GPU device (0 = first GPU, 'cpu' for CPU)
    WORKERS = 8  # Number of dataloader workers
    SAVE_PERIOD = 5  # Save checkpoint every N epochs
    
    # Validation
    VAL = True
    PLOTS = True
    SAVE = True
    
    # Advanced settings
    AMP = True  # Automatic Mixed Precision
    FRACTION = 1.0  # Dataset fraction to use
    PROFILE = False  # Profile ONNX/TensorRT speed
    FREEZE = None  # Layers to freeze
    
    # Resume training
    RESUME = False
    RESUME_PATH = None


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def check_gpu():
    """Check GPU availability and memory"""
    if torch.cuda.is_available():
        device = torch.cuda.current_device()
        gpu_name = torch.cuda.get_device_name(device)
        total_memory = torch.cuda.get_device_properties(device).total_memory / 1e9
        print(f"✓ GPU Available: {gpu_name}")
        print(f"✓ Total Memory: {total_memory:.2f} GB")
        return True
    else:
        print("⚠ No GPU available, using CPU")
        return False


def verify_dataset(dataset_root, data_yaml_path):
    """Verify dataset structure and data.yaml"""
    print("\n" + "="*70)
    print("DATASET VERIFICATION")
    print("="*70)
    
    dataset_path = Path(dataset_root)
    
    if not dataset_path.exists():
        raise FileNotFoundError(f"Dataset not found at {dataset_root}")
    
    # Check for data.yaml
    yaml_path = Path(data_yaml_path)
    if not yaml_path.exists():
        print(f"✗ data.yaml not found at {data_yaml_path}")
        print(f"\nGenerating data.yaml automatically...")
        
        # Auto-generate yaml
        try:
            from generate_data_yaml import generate_data_yaml
            generated_yaml = generate_data_yaml(dataset_root, data_yaml_path)
            print(f"✓ Generated: {generated_yaml}")
        except Exception as e:
            print(f"\n✗ Failed to auto-generate data.yaml: {str(e)}")
            print(f"\nPlease run manually:")
            print(f"  python generate_data_yaml.py '{dataset_root}'")
            raise
    else:
        print(f"✓ Found data.yaml at {data_yaml_path}")
    
    # Check for train and valid directories
    train_path = dataset_path / 'train'
    valid_path = dataset_path / 'valid'
    
    if not train_path.exists():
        raise FileNotFoundError(f"Training directory not found at {train_path}")
    
    # Count classes and images
    train_classes = [d for d in train_path.iterdir() if d.is_dir()]
    num_train_classes = len(train_classes)
    
    # Count images in each split
    train_images = sum([len(list(cls_dir.glob('*.JPG'))) + len(list(cls_dir.glob('*.jpg'))) + 
                        len(list(cls_dir.glob('*.jpeg'))) + len(list(cls_dir.glob('*.png'))) 
                        for cls_dir in train_classes])
    
    print(f"✓ Dataset root: {dataset_root}")
    print(f"✓ Training classes: {num_train_classes}")
    print(f"✓ Training images: {train_images}")
    
    if valid_path.exists():
        valid_classes = [d for d in valid_path.iterdir() if d.is_dir()]
        valid_images = sum([len(list(cls_dir.glob('*.JPG'))) + len(list(cls_dir.glob('*.jpg'))) + 
                           len(list(cls_dir.glob('*.jpeg'))) + len(list(cls_dir.glob('*.png'))) 
                           for cls_dir in valid_classes])
        print(f"✓ Validation classes: {len(valid_classes)}")
        print(f"✓ Validation images: {valid_images}")
    else:
        print("⚠ No validation directory found")
    
    # Print sample classes
    print(f"\nSample classes (first 10):")
    for i, cls_dir in enumerate(sorted(train_classes)[:10], 1):
        img_count = len(list(cls_dir.glob('*.JPG'))) + len(list(cls_dir.glob('*.jpg'))) + \
                   len(list(cls_dir.glob('*.jpeg'))) + len(list(cls_dir.glob('*.png')))
        print(f"  {i}. {cls_dir.name}: {img_count} images")
    
    return num_train_classes, train_images


def print_training_config(config):
    """Print training configuration"""
    print("\n" + "="*70)
    print("TRAINING CONFIGURATION")
    print("="*70)
    print(f"Model: {config.MODEL_NAME}")
    print(f"Task: {config.TASK}")
    print(f"Epochs: {config.EPOCHS}")
    print(f"Batch size: {config.BATCH_SIZE}")
    print(f"Image size: {config.IMG_SIZE}")
    print(f"Optimizer: {config.OPTIMIZER}")
    print(f"Initial LR: {config.LR0}")
    print(f"Device: {'GPU' if config.DEVICE == 0 else 'CPU'}")
    print(f"Workers: {config.WORKERS}")
    print(f"Patience: {config.PATIENCE}")
    print(f"AMP: {config.AMP}")
    print("="*70)


def setup_project_directory(project_root):
    """Setup project directory structure"""
    project_path = Path(project_root)
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create subdirectories
    (project_path / 'runs').mkdir(exist_ok=True)
    (project_path / 'models').mkdir(exist_ok=True)
    (project_path / 'logs').mkdir(exist_ok=True)
    
    print(f"\n✓ Project directory setup at {project_root}")
    return project_path


# ============================================================================
# TRAINING FUNCTION
# ============================================================================

def train_yolov8(config):
    """
    Train YOLOv8 classification model
    
    Args:
        config: Configuration object
    
    Returns:
        YOLO model and results
    """
    print("\n" + "="*70)
    print("INITIALIZING YOLOV8 TRAINING")
    print("="*70)
    
    # Initialize model
    print(f"\nLoading model: {config.MODEL_NAME}")
    model = YOLO(config.MODEL_NAME)
    
    # Setup training arguments
    train_args = {
        'data': config.DATA_YAML,  # Use data.yaml path instead of directory
        'epochs': config.EPOCHS,
        'imgsz': config.IMG_SIZE,
        'batch': config.BATCH_SIZE,
        'device': config.DEVICE,
        'workers': config.WORKERS,
        'optimizer': config.OPTIMIZER,
        'lr0': config.LR0,
        'lrf': config.LRF,
        'momentum': config.MOMENTUM,
        'weight_decay': config.WEIGHT_DECAY,
        'patience': config.PATIENCE,
        'save': config.SAVE,
        'save_period': config.SAVE_PERIOD,
        'val': config.VAL,
        'plots': config.PLOTS,
        'amp': config.AMP,
        'fraction': config.FRACTION,
        'project': config.PROJECT_ROOT,
        'name': f'plant_disease_classification_{datetime.now().strftime("%Y%m%d_%H%M%S")}',
        'exist_ok': True,
        'pretrained': True,
        'verbose': True,
    }
    
    # Add optional arguments
    if config.RESUME and config.RESUME_PATH:
        train_args['resume'] = config.RESUME_PATH
    
    if config.FREEZE is not None:
        train_args['freeze'] = config.FREEZE
    
    # Print training arguments
    print("\nTraining arguments:")
    for key, value in train_args.items():
        print(f"  {key}: {value}")
    
    print("\n" + "="*70)
    print("STARTING TRAINING")
    print("="*70)
    
    # Start training
    results = model.train(**train_args)
    
    print("\n" + "="*70)
    print("TRAINING COMPLETE!")
    print("="*70)
    
    return model, results


# ============================================================================
# VALIDATION FUNCTION
# ============================================================================

def validate_model(model, config):
    """
    Validate trained model
    
    Args:
        model: Trained YOLO model
        config: Configuration object
    
    Returns:
        Validation results
    """
    print("\n" + "="*70)
    print("VALIDATING MODEL")
    print("="*70)
    
    # Validation arguments
    val_args = {
        'data': config.DATA_YAML,  # Use data.yaml instead of directory
        'imgsz': config.IMG_SIZE,
        'batch': config.BATCH_SIZE,
        'device': config.DEVICE,
        'workers': config.WORKERS,
        'plots': True,
        'verbose': True,
    }
    
    # Run validation
    results = model.val(**val_args)
    
    print("\n" + "="*70)
    print("VALIDATION COMPLETE!")
    print("="*70)
    
    return results


# ============================================================================
# EXPORT FUNCTION
# ============================================================================

def export_model(model, config):
    """
    Export model to different formats
    
    Args:
        model: Trained YOLO model
        config: Configuration object
    """
    print("\n" + "="*70)
    print("EXPORTING MODEL")
    print("="*70)
    
    export_formats = ['onnx', 'torchscript']
    
    for fmt in export_formats:
        try:
            print(f"\nExporting to {fmt.upper()}...")
            model.export(format=fmt, imgsz=config.IMG_SIZE)
            print(f"✓ Successfully exported to {fmt.upper()}")
        except Exception as e:
            print(f"✗ Failed to export to {fmt.upper()}: {str(e)}")
    
    print("\n" + "="*70)
    print("EXPORT COMPLETE!")
    print("="*70)


# ============================================================================
# MAIN FUNCTION
# ============================================================================

def main():
    """Main training pipeline"""
    
    print("\n" + "="*70)
    print("YOLOv8 PLANT DISEASE CLASSIFICATION - TRAINING PIPELINE")
    print("="*70)
    print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Initialize configuration
    config = Config()
    
    # Check GPU
    check_gpu()
    
    # Verify dataset (will auto-generate data.yaml if missing)
    num_classes, num_images = verify_dataset(config.DATASET_ROOT, config.DATA_YAML)
    
    # Setup project directory
    project_path = setup_project_directory(config.PROJECT_ROOT)
    
    # Print configuration
    print_training_config(config)
    
    # Train model
    model, train_results = train_yolov8(config)
    
    # Validate model
    val_results = validate_model(model, config)
    
    # Print results summary
    print("\n" + "="*70)
    print("RESULTS SUMMARY")
    print("="*70)
    print(f"Best model saved at: {model.trainer.best}")
    print(f"Results directory: {model.trainer.save_dir}")
    
    # Export model (optional)
    user_input = input("\nDo you want to export the model to ONNX/TorchScript? (y/n): ")
    if user_input.lower() == 'y':
        export_model(model, config)
    
    print("\n" + "="*70)
    print("PIPELINE COMPLETE!")
    print(f"End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*70)
    
    return model, train_results, val_results


if __name__ == "__main__":
    try:
        model, train_results, val_results = main()
    except KeyboardInterrupt:
        print("\n\nTraining interrupted by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n\nError during training: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
